---
title: Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/blog"
url: https://zhiyongc.github.io/
theme_settings:
  title: Zhiyong's blog
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: 
  description: A website with blog posts and pages
  header_text: |-
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image: 
  footer_text: 
  rss: false
  email_address: zhiyongc@uw.edu
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  gitlab: 
  github: zhiyongc
  gitter: 
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: 
  wordpress: 
  youtube: 
  google_analytics: 
  disqus_shortname: zhiyongc-github-io-blog
  katex: true
  search: false
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next_post: Next post
  str_previous_post: Previous post
  str_next_page: Next
  str_previous_page: Prev
  str_continue_reading: Continue reading
  str_javascript_required_disqus: zhiyongc-github-io-blog
  str_search_no_results: No results found.
  google_fonts: Source+Sans+Pro:400,700,700italic,400italic
  post_navigation: true
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
